server: 
  port: 9090
spring:
  application:
    name: lostitems
  datasource:
    url: jdbc:mysql://localhost:3306/items
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
